name: Updating Gantt Chart
env: 
        NOTION_TOKEN : ${{secrets.NOTION_TOKEN}}
        PAGE_ID : ${{secrets.PAGE_ID}}

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.11
      uses: actions/setup-python@v3
      with:
        python-version: "3.11"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install datetime
        pip install requests
        pip install python-dotenv
      
    - name: Run file
      run: python main.py

    - name: Generate Image
      run: | 
        npm install -g @mermaid-js/mermaid-cli
        mv mermaidCode.txt  mermaidCode.mmd 
        ls
        mmdc -i mermaidCode.mmd  -o output.svg -w 1024 -H 768
        ls
    
    - name: Archive Image
      uses: actions/upload-artifact@v3
      with:
        name: gantt-chart
        path: output.svg

